services:
  agent-adk:
    build: ./agent_1_adk
    ports: ["8001:8001"]
    environment:
      - AGENT_LLAMAINDEX_URL=http://agent-llamaindex:8002
      - AGENT_LANGGRAPH_URL=http://agent-langgraph:8003
      - AGENT_CREWAI_URL=http://agent-crewai:8004
      - MCP_SERVER_URL=http://finsight-mcp:8010/sse
    depends_on:
      - agent-llamaindex
      - agent-langgraph
      - agent-crewai
      - finsight-mcp

  agent-llamaindex:
    build: ./agent_2_llamaindex
    ports: ["8002:8002"]
    environment:
      - CHROMA_DIR=/data/chroma
      - MCP_SERVER_URL=http://finsight-mcp:8010/sse
    volumes:
      - chroma_data:/data/chroma
    depends_on:
      - finsight-mcp

  agent-langgraph:
    build: ./agent_3_langgraph
    ports: ["8003:8003"]
    environment:
      - MCP_SERVER_URL=http://finsight-mcp:8010/sse
    depends_on:
      - finsight-mcp

  agent-crewai:
    build: ./agent_4_crewai
    ports: ["8004:8004"]
    environment:
      - MCP_SERVER_URL=http://finsight-mcp:8010/sse
    depends_on:
      - finsight-mcp

  finsight-mcp:
    build: ./mcp_servers
    ports: ["8010:8010"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

volumes:
  chroma_data:
