"""Shared data model for investment report generation."""

from __future__ import annotations

from dataclasses import dataclass, field

_DEFAULT_DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It does not constitute financial advice. Past performance is not indicative of future results. "  # noqa: E501
    "Always consult a qualified financial advisor before making investment decisions."
)

_MAX_SLIDE_CHARS = 1200


# ── Parsed report structure ───────────────────────────────────────────────────


@dataclass
class Section:
    title: str
    body: str


@dataclass
class ExtractionCtx:
    """Carries state through the staged extraction pipeline."""

    data: DeckData
    text: str
    sections: list[Section]
    tables: list[ParsedTable]
    extracted_metrics: dict[str, str] = field(default_factory=dict)


@dataclass
class ParsedTable:
    headers: list[str]
    rows: list[dict[str, str]]


@dataclass
class DeckData:
    """Enriched report data matching the deck template slides."""

    ticker: str
    company_name: str
    sector: str
    exchange: str
    recommendation: str
    confidence: float
    analysis_date: str
    executive_summary: str
    # Slide 2: KPI chips
    kpi_chips: list[dict] = field(default_factory=list)
    # Slide 4: Financials table rows [(metric, current, yoy_change)]
    financials: list[tuple[str, str, str]] = field(default_factory=list)
    # Slide 5: Valuation table rows [(metric, value)] + scenario cards
    valuation_table: list[tuple[str, str]] = field(default_factory=list)
    scenarios: dict = field(default_factory=dict)
    # Slide 6: Scorecard [(dimension, rating, badge_type)]
    scorecard: list[tuple[str, str, str]] = field(default_factory=list)
    # Slide 7: Peer comparison [(metric, ticker_val, peer1_name, peer1_val, peer2_name, peer2_val)]
    peers: list[dict] = field(default_factory=list)
    peer_names: list[str] = field(default_factory=list)
    # Slide 8: Risk-reward
    opportunities: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    # R.3: provenance flags — set True when real extraction produced items
    risks_extracted: bool = False
    opportunities_extracted: bool = False
    # Extra content sections (overflow)
    sections: list[Section] = field(default_factory=list)
    # Analytics Agent chart payloads (candlestick, line, area)
    charts: list[dict] = field(default_factory=list)
    # Technical indicators table [(indicator, value, signal)]
    technicals_table: list[tuple[str, str, str]] = field(default_factory=list)
    # Behavioral signals — insider, options, analyst [(category, metric, value)]
    signals_table: list[tuple[str, str, str]] = field(default_factory=list)
    # Forecast chart data for Chart.js
    forecast_chart: dict = field(default_factory=dict)
    # Monte Carlo summary
    monte_carlo_summary: dict = field(default_factory=dict)
    # Stress test scenarios [(scenario_name, decline_pct, projected_price)]
    stress_scenarios: list[tuple[str, str, str]] = field(default_factory=list)
    # DCF valuation breakdown [(metric, value)]
    dcf_breakdown: list[tuple[str, str]] = field(default_factory=list)
    # Statistical summary [(metric, value, interpretation)]
    stats_table: list[tuple[str, str, str]] = field(default_factory=list)
    # Anomaly alerts [{type, description, severity}]
    anomaly_alerts: list[dict] = field(default_factory=list)
    # Trend analysis dashboard
    trend_data: dict = field(default_factory=dict)
    # Reviewer cross-validation
    reviewer_contradictions: list[dict] = field(default_factory=list)
    reviewer_verifications: list[dict] = field(default_factory=list)
    reviewer_confidence: dict = field(default_factory=dict)
    reviewer_validation: dict = field(default_factory=dict)
    # Market macro context
    macro_regime: str = ""
    disclaimer: str = _DEFAULT_DISCLAIMER
