"""Generate PPTX, DOCX, and HTML investment reports from brief_json data.

Public API:
    generate_pptx(brief_data, ticker, recommendation, confidence, analysis_date) -> BytesIO
    generate_docx(brief_data, ticker, recommendation, confidence, analysis_date) -> BytesIO
    generate_html(brief_data, ticker, recommendation, confidence, analysis_date) -> str

Handles both brief_json shapes:
  - Full InvestmentBrief JSON (has rag_insights, quant_metrics, etc.)
  - Minimal {"response_text": "..."} (markdown text from LLM synthesis)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from io import BytesIO
from types import SimpleNamespace
from typing import Optional

# ── Colour palette — modern navy/blue (matches deck template) ────────────────
_NAVY = "0C1425"
_NAVY_MID = "162036"
_BLUE = "3B7DFA"
_BLUE_LIGHT = "E8F0FE"
_GREEN = "22C55E"
_GREEN_DARK = "15803D"
_AMBER = "F59E0B"
_RED = "EF4444"
_TEXT = "1A2236"
_TEXT_MID = "475569"
_TEXT_LIGHT = "94A3B8"
_BORDER = "E2E8F0"
_SURFACE = "F1F5F9"
_WHITE = "FFFFFF"

# Badge colours
_BADGE_STRONG_BG = "DCFCE7"
_BADGE_STRONG_FG = "15803D"
_BADGE_BULLISH_BG = "DBEAFE"
_BADGE_BULLISH_FG = "1D4ED8"
_BADGE_EXPENSIVE_BG = "FEF3C7"
_BADGE_EXPENSIVE_FG = "92400E"
_BADGE_MODERATE_BG = "F1F5F9"
_BADGE_MODERATE_FG = "475569"

# Opportunity/Risk column colours
_OPP_BG = "F0FDF4"
_OPP_BORDER = "BBF7D0"
_RISK_BG = "FEF2F2"
_RISK_BORDER = "FECACA"

_SIGNAL_COLOURS = {
    "BUY": (_GREEN_DARK, _BADGE_STRONG_BG),
    "HOLD": (_BADGE_BULLISH_FG, _BADGE_BULLISH_BG),
    "SELL": (_RED, _RISK_BG),
}

# DOCX uses a slightly different palette (kept for backward compat)
_DOCX_NAVY = "0C1425"
_DOCX_BLUE = "3B7DFA"
_DOCX_SURFACE = "F1F5F9"

_DEFAULT_DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It does not constitute financial advice. Past performance is not indicative of future results. "
    "Always consult a qualified financial advisor before making investment decisions."
)

_MAX_SLIDE_CHARS = 1200


# ── Parsed report structure ───────────────────────────────────────────────────

@dataclass
class Section:
    title: str
    body: str


@dataclass
class DeckData:
    """Enriched report data matching the deck template slides."""
    ticker: str
    company_name: str
    sector: str
    exchange: str
    recommendation: str
    confidence: float
    analysis_date: str
    executive_summary: str
    # Slide 2: KPI chips
    kpi_chips: list[dict] = field(default_factory=list)
    # Slide 4: Financials table rows [(metric, current, yoy_change)]
    financials: list[tuple[str, str, str]] = field(default_factory=list)
    # Slide 5: Valuation table rows [(metric, value)] + scenario cards
    valuation_table: list[tuple[str, str]] = field(default_factory=list)
    scenarios: dict = field(default_factory=dict)
    # Slide 6: Scorecard [(dimension, rating, badge_type)]
    scorecard: list[tuple[str, str, str]] = field(default_factory=list)
    # Slide 7: Peer comparison [(metric, ticker_val, peer1_name, peer1_val, peer2_name, peer2_val)]
    peers: list[dict] = field(default_factory=list)
    peer_names: list[str] = field(default_factory=list)
    # Slide 8: Risk-reward
    opportunities: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    # Extra content sections (overflow)
    sections: list[Section] = field(default_factory=list)
    disclaimer: str = _DEFAULT_DISCLAIMER


# ── Content extraction helpers ────────────────────────────────────────────────

def _strip_markdown(text: str) -> str:
    """Remove markdown syntax, keeping plain readable text."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    text = re.sub(r"^[-|:]+$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"^[-*+]\s+", "• ", text, flags=re.MULTILINE)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _parse_markdown_sections(text: str) -> list[Section]:
    """Split text into sections. Handles ## headers and **Bold:** headers."""
    # First try ## headers
    parts = re.split(r"\n##\s+", "\n" + text)
    if len(parts) > 1:
        sections: list[Section] = []
        for part in parts:
            part = part.strip()
            if not part:
                continue
            lines = part.split("\n", 1)
            title = _strip_markdown(lines[0].strip())
            body = _strip_markdown(lines[1].strip()) if len(lines) > 1 else ""
            if title and (body or title):
                sections.append(Section(title=title, body=body))
        return sections

    # Fallback: split on **Bold Header:** or "Label:" at line start followed by content
    header_pat = re.compile(
        r"^(?:\*\*(.+?)\*\*\s*:?\s*$|([A-Z][A-Za-z\s/&]+?):\s*$)",
        re.MULTILINE,
    )
    matches = list(header_pat.finditer(text))
    if not matches:
        return []

    sections = []
    for i, m in enumerate(matches):
        title = (m.group(1) or m.group(2)).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = _strip_markdown(text[start:end].strip())
        if title and len(body) > 10:
            sections.append(Section(title=title, body=body))
    return sections


def _fmt_pct(val: float | None, mult100: bool = False) -> str:
    if val is None:
        return "N/A"
    v = val * 100 if mult100 else val
    sign = "+" if v > 0 else ""
    return f"{sign}{v:.1f}%"


def _fmt_dollar(val: float | None) -> str:
    if val is None:
        return "N/A"
    return f"${val:,.2f}"


def _extract_bullets(text: str) -> list[str]:
    """Extract bullet points from markdown-like text, labeled lines, or numbered items."""
    bullets = []
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        # Markdown bullets: - * + •
        m = re.match(r"^[•\-*+]\s+(.+)", line)
        if m:
            item = re.sub(r"\*\*(.+?)\*\*", r"\1", m.group(1).strip())
            if len(item) > 5:
                bullets.append(item)
            continue
        # Numbered bullets: 1. 2. etc
        m = re.match(r"^\d+[.)]\s+(.+)", line)
        if m:
            item = re.sub(r"\*\*(.+?)\*\*", r"\1", m.group(1).strip())
            if len(item) > 5:
                bullets.append(item)
            continue
        # "Label: description" lines (e.g., "Macro Volatility: Sustained high VIX...")
        m = re.match(r"^([A-Z][A-Za-z\s]+):\s+(.+)", line)
        if m and len(m.group(2)) > 10:
            item = m.group(2).strip()
            item = re.sub(r"\*\*(.+?)\*\*", r"\1", item)
            bullets.append(item)
    return bullets


_ticker_cache: dict[str, tuple[str, str, str]] = {}

_EXCHANGE_MAP = {
    "NMS": "NASDAQ", "NGM": "NASDAQ", "NCM": "NASDAQ",
    "NYQ": "NYSE", "NYS": "NYSE", "PCX": "NYSE ARCA",
    "BTS": "CBOE", "LSE": "LSE", "TYO": "TSE",
}


def _resolve_ticker_info(ticker: str, text: str) -> tuple[str, str, str]:
    """Return (company_name, sector, exchange). Tries yfinance → regex → ticker symbol."""
    ticker = ticker.upper()
    if ticker in _ticker_cache:
        return _ticker_cache[ticker]
    try:
        import yfinance as yf
        info = yf.Ticker(ticker).info
        name = info.get("longName") or info.get("shortName") or ""
        sector = info.get("sector") or ""
        raw_exchange = info.get("exchange") or ""
        exchange = _EXCHANGE_MAP.get(raw_exchange, raw_exchange)
        if name:
            _ticker_cache[ticker] = (name, sector, exchange)
            return _ticker_cache[ticker]
    except Exception:
        pass
    for pat in [
        r"(?:for|about|of)\s+([A-Z][A-Za-z\s&.]+?)\s*\(" + re.escape(ticker) + r"\)",
        r"([A-Z][A-Za-z\s&.]+?)\s*\(" + re.escape(ticker) + r"\)",
    ]:
        m = re.search(pat, text)
        if m:
            _ticker_cache[ticker] = (m.group(1).strip(), "", "")
            return _ticker_cache[ticker]
    return (ticker, "", "")


def _parse_markdown_tables(text: str) -> tuple[str, list[dict]]:
    """Extract markdown tables into structured dicts. Returns (cleaned_text, all_rows)."""
    table_pattern = re.compile(r"((?:^\|.+\|\s*\n)+)", re.MULTILINE)
    parsed_tables: list[list[dict]] = []
    for match in table_pattern.finditer(text):
        block = match.group(1)
        lines = [ln.strip() for ln in block.strip().split("\n") if ln.strip()]
        data_lines = [ln for ln in lines if not re.match(r"^\|(?:[\s\-:]+\|)+$", ln)]
        if len(data_lines) < 2:
            continue
        headers = [c.strip() for c in data_lines[0].split("|")[1:-1]]
        rows = []
        for line in data_lines[1:]:
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if len(cells) == len(headers):
                rows.append(dict(zip(headers, cells)))
        if rows:
            parsed_tables.append(rows)
    cleaned = table_pattern.sub("", text)
    return cleaned, [row for table in parsed_tables for row in table]


def _extract_deck_data(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> DeckData:
    rec = recommendation.upper() if recommendation else "UNKNOWN"
    response_text = brief_data.get("response_text", "")
    name, sector, exchange = _resolve_ticker_info(ticker, response_text)

    data = DeckData(
        ticker=ticker,
        company_name=name,
        sector=sector,
        exchange=exchange,
        recommendation=rec,
        confidence=confidence,
        analysis_date=analysis_date,
        executive_summary="",
    )

    # ── Structured InvestmentBrief path ──────────────────────────────────────
    if "final_recommendation" in brief_data or "rag_insights" in brief_data:
        rationale = brief_data.get("recommendation_rationale", "")
        data.executive_summary = _strip_markdown(rationale[:800]) if rationale else ""
        data.disclaimer = brief_data.get("disclaimer", _DEFAULT_DISCLAIMER)

        qm = brief_data.get("quant_metrics", {})
        si = brief_data.get("sentiment_intelligence", {})
        ri = brief_data.get("rag_insights", {})

        # KPI chips
        if ri.get("revenue_growth_yoy") is not None:
            data.kpi_chips.append({"label": "Revenue Growth", "value": _fmt_pct(ri["revenue_growth_yoy"], True), "context": "Year-over-year", "positive": ri["revenue_growth_yoy"] > 0})
        if qm.get("sharpe_ratio") is not None:
            data.kpi_chips.append({"label": "Sharpe Ratio", "value": f"{qm['sharpe_ratio']:.2f}", "context": "Risk-adjusted return", "positive": qm["sharpe_ratio"] > 0})
        if si.get("avg_price_target"):
            data.kpi_chips.append({"label": "Analyst Target", "value": _fmt_dollar(si["avg_price_target"]), "context": si.get("analyst_consensus", ""), "positive": True})
        if qm.get("annual_volatility") is not None:
            data.kpi_chips.append({"label": "Annual Volatility", "value": _fmt_pct(qm["annual_volatility"], True), "context": "Annualized", "positive": qm["annual_volatility"] < 0.25})

        # Financials table
        if ri.get("revenue_growth_yoy") is not None:
            data.financials.append(("Revenue Growth", _fmt_pct(ri["revenue_growth_yoy"], True), "YoY"))
        if qm.get("beta") is not None:
            data.financials.append(("Beta", f"{qm['beta']:.2f}", "vs. S&P 500"))
        if qm.get("sharpe_ratio") is not None:
            data.financials.append(("Sharpe Ratio", f"{qm['sharpe_ratio']:.2f}", "Risk-Adjusted"))
        if qm.get("var_95_daily") is not None:
            data.financials.append(("VaR (95%, daily)", _fmt_pct(qm["var_95_daily"], True), "Daily"))

        # Valuation
        if qm.get("dcf_intrinsic_value"):
            data.valuation_table.append(("DCF Fair Value", _fmt_dollar(qm["dcf_intrinsic_value"])))
            data.scenarios["dcf"] = _fmt_dollar(qm["dcf_intrinsic_value"])
        if si.get("avg_price_target"):
            data.valuation_table.append(("Analyst Price Target", _fmt_dollar(si["avg_price_target"])))
            data.scenarios["base"] = _fmt_dollar(si["avg_price_target"])

        # Scorecard
        data.scorecard.append(("Risk Profile", "Low" if (qm.get("annual_volatility") or 0) < 0.2 else "Moderate" if (qm.get("annual_volatility") or 0) < 0.35 else "High", "moderate"))
        if si.get("analyst_consensus"):
            data.scorecard.append(("Analyst Consensus", si["analyst_consensus"], "bullish" if "buy" in si["analyst_consensus"].lower() else "moderate"))
        if si.get("insider_signal"):
            data.scorecard.append(("Insider Signal", si["insider_signal"], "strong" if "buy" in si["insider_signal"].lower() else "moderate"))
        data.scorecard.append(("Recommendation", rec, "strong" if rec == "BUY" else "bullish" if rec == "HOLD" else "expensive"))

        # Risks and opportunities
        ri_risks = ri.get("key_risks", [])
        si_risks = si.get("key_risks", [])
        data.risks = (ri_risks + si_risks)[:5] or ["Market volatility", "Regulatory changes"]
        cats = si.get("key_catalysts", [])
        data.opportunities = cats[:5] or ["Strong operational execution"]

        # Extra sections
        if ri.get("forward_guidance"):
            data.sections.append(Section("Forward Guidance", ri["forward_guidance"]))
        if si.get("narrative"):
            data.sections.append(Section("Market Narrative", si["narrative"]))

        return data

    # ── Minimal response_text path ────────────────────────────────────────────
    response_text = brief_data.get("response_text", "")
    if not response_text:
        data.executive_summary = "No analysis content available."
        return data

    # Parse tables FIRST — before _strip_markdown destroys them
    cleaned_text, table_rows = _parse_markdown_tables(response_text)
    sections = _parse_markdown_sections(cleaned_text)

    # Try to extract structured data from the markdown text
    _enrich_from_markdown(data, cleaned_text, sections, table_rows=table_rows)

    if not data.executive_summary and sections:
        first = sections[0]
        data.executive_summary = (first.body or first.title)[:800]
        data.sections = sections[1:]
    elif not data.executive_summary:
        data.executive_summary = _strip_markdown(cleaned_text[:800])

    return data


def _enrich_from_markdown(
    data: DeckData, text: str, sections: list[Section], table_rows: list[dict] = None
) -> None:
    """Extract KPIs, scorecard ratings, risks, and opportunities from text.

    Handles multiple formats:
      - "revenue growth (85.2%)"    — value in parens after label
      - "Revenue Growth: +7.3%"    — colon-separated
      - "ROE=24.1%"                — equals-separated
      - "$298.42"                  — dollar amounts
    """
    # ── Use pre-parsed table data first ─────────────────────────────────────
    if table_rows:
        for row in table_rows:
            metric = row.get("Metric") or row.get("metric") or ""
            for val_key in ("Current", "Value", "current", "value"):
                if val_key in row and metric:
                    data.financials.append((metric, row[val_key], row.get("YoY Change", row.get("Context", ""))))
                    break
            peer_cols = [k for k in row.keys() if k not in ("Metric", "metric", "") and k.upper() != data.ticker]
            if peer_cols and metric:
                for peer_name in peer_cols[:2]:
                    if peer_name not in data.peer_names:
                        data.peer_names.append(peer_name)
                # Build deck.peers with expected structure: {metric, col0, col1, col2, ...}
                peer_row = {"metric": metric}
                ticker_val = row.get(data.ticker, row.get("Current", row.get("current", "")))
                if ticker_val:
                    peer_row["col0"] = ticker_val
                for ci, pn in enumerate(peer_cols[:2]):
                    if pn in row:
                        peer_row[f"col{ci + 1}"] = row[pn]
                if len(peer_row) > 1:
                    data.peers.append(peer_row)

    # ── Extract numeric metrics ──────────────────────────────────────────────
    # Each pattern list is tried in order; first match wins for that metric.
    metric_patterns: list[tuple[str, list[str], bool]] = [
        ("Revenue Growth", [
            r"revenue\s+growth\s*[\(:]\s*([+-]?\d+\.?\d*)\s*%",
            r"revenue\s+growth[:\s]+([+-]?\d+\.?\d*)\s*%",
        ], True),
        ("ROE", [
            r"ROE\s*[\(:]\s*([+-]?\d+\.?\d*)\s*%",
            r"(?:ROE|return\s+on\s+equity)[:\s]+([+-]?\d+\.?\d*)\s*%",
        ], True),
        ("Operating Margin", [
            r"operating\s+margin\s*[\(:]\s*([+-]?\d+\.?\d*)\s*%",
            r"operating\s+margin[:\s]+([+-]?\d+\.?\d*)\s*%",
        ], True),
        ("P/E Ratio", [
            r"P/?E\s*[\(:=]\s*([+-]?\d+\.?\d*)",
            r"P/?E\s+(?:ratio\s*)?[:\s]+([+-]?\d+\.?\d*)",
            r"trailing\s+PE\s*[\(:]\s*([+-]?\d+\.?\d*)",
        ], False),
        ("Beta", [
            r"[Bb]eta\s*[\(:=]\s*([+-]?\d+\.?\d*)",
            r"[Bb]eta[:\s]+([+-]?\d+\.?\d*)",
        ], False),
        ("Sharpe Ratio", [
            r"[Ss]harpe\s+[Rr]atio\s*[\(:=]\s*([+-]?\d+\.?\d*)",
            r"[Ss]harpe\s+[Rr]atio[:\s]+([+-]?\d+\.?\d*)",
        ], False),
        ("RSI", [
            r"RSI\s*[\(:=]\s*([+-]?\d+\.?\d*)",
        ], False),
        ("Volatility", [
            r"(?:annual\s+)?volatility\s*[\(:]\s*([+-]?\d+\.?\d*)\s*%",
            r"(?:annual\s+)?volatility[:\s]+([+-]?\d+\.?\d*)\s*%",
        ], True),
        ("Debt/Equity", [
            r"(?:debt[/\\]equity|D/E)\s*[\(:=]\s*([+-]?\d+\.?\d*)",
        ], False),
        ("Dividend Yield", [
            r"dividend\s+yield\s*[\(:=]\s*([+-]?\d+\.?\d*)\s*%",
        ], True),
        ("EPS", [
            r"(?:diluted\s+)?EPS\s*[\(:=]\s*\$?\s*([+-]?\d+\.?\d*)",
        ], False),
        ("Current Ratio", [
            r"current\s+ratio\s*[\(:=]\s*([+-]?\d+\.?\d*)",
        ], False),
        ("Net Margin", [
            r"net\s+(?:profit\s+)?margin\s*[\(:=]\s*([+-]?\d+\.?\d*)\s*%",
        ], True),
    ]

    extracted: dict[str, str] = {}
    for label, pats, is_pct in metric_patterns:
        for pat in pats:
            m = re.search(pat, text, re.IGNORECASE)
            if m:
                val = m.group(1)
                extracted[label] = f"{val}%" if is_pct else val
                break

    # Priority-based KPI chip selection
    _kpi_context = {
        "Revenue Growth": "YoY",
        "ROE": "Return on Equity",
        "Operating Margin": "Profitability",
        "P/E Ratio": "Valuation",
        "Beta": "Mkt sensitivity",
        "RSI": "Momentum",
        "Sharpe Ratio": "Risk-adj return",
        "Volatility": "Annualized",
        "Debt/Equity": "Leverage",
        "Dividend Yield": "Income",
        "EPS": "Earnings per share",
        "Current Ratio": "Liquidity",
        "Net Margin": "Profitability",
    }
    _KPI_PRIORITY = [
        "Revenue Growth", "ROE", "Operating Margin", "P/E Ratio",
        "Sharpe Ratio", "Beta", "Dividend Yield", "RSI",
        "Volatility", "EPS", "Net Margin", "Debt/Equity", "Current Ratio",
    ]
    selected = [lbl for lbl in _KPI_PRIORITY if lbl in extracted][:4]
    for lbl in extracted:
        if lbl not in selected and len(selected) < 4:
            selected.append(lbl)
    for label in selected:
        val = extracted[label]
        data.kpi_chips.append({"label": label, "value": val, "context": _kpi_context.get(label, ""), "positive": not val.startswith("-")})

    # ── Extract price targets / valuation ────────────────────────────────────
    # avg target / price target: "$298.42" or "target: $298.42"
    target_pats = [
        r"(?:avg\.?\s+)?(?:price\s+)?target\s*[:\s]*\$\s*([\d,]+\.?\d*)",
        r"(?:target\s+price|price\s+target|median\s+target)\s*[:\s]*\$\s*([\d,]+\.?\d*)",
    ]
    for pat in target_pats:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            data.valuation_table.append(("Analyst Price Target", f"${m.group(1)}"))
            data.scenarios["base"] = f"${m.group(1)}"
            break

    # Upside potential: "45.5% upside" or "upside potential (45.5%)"
    upside_pats = [
        r"(\d+\.?\d*)\s*%\s+upside\s+potential",
        r"upside\s+potential\s*[\(:]\s*(\d+\.?\d*)\s*%",
        r"expected\s+(?:upside|return)\s*[\(:]\s*(\d+\.?\d*)\s*%",
        r"expected\s+(?:upside|return)[:\s]+([+-]?\d+\.?\d*)\s*%",
        r"median\s+upside[:\s]+([+-]?\d+\.?\d*)\s*%",
    ]
    for pat in upside_pats:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            data.valuation_table.append(("Expected Upside", f"+{m.group(1)}%"))
            break

    dcf_pats = [
        r"DCF\s+(?:fair\s+value|intrinsic\s+value)\s*[:\s]*\$\s*([\d,]+\.?\d*)",
        r"(?:fair\s+value|intrinsic\s+value)\s*[:\s]*\$\s*([\d,]+\.?\d*)",
    ]
    for pat in dcf_pats:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            data.valuation_table.append(("DCF Fair Value", f"${m.group(1)}"))
            data.scenarios["dcf"] = f"${m.group(1)}"
            break

    bull_m = re.search(r"bull\s+case[:\s]*\$\s*([\d,]+\.?\d*)", text, re.IGNORECASE)
    if bull_m:
        data.valuation_table.append(("Bull Case Target", f"${bull_m.group(1)}"))
        data.scenarios["bull"] = f"${bull_m.group(1)}"

    prob_pats = [
        r"prob(?:ability)?\s+(?:of\s+)?(?:positive\s+)?(?:return|profit)\s*[:\s]+(\d+\.?\d*)\s*%",
        r"prob(?:ability)?\s+(?:of\s+)?(?:positive\s+)?(?:return|profit)\s*[\(]\s*(\d+\.?\d*)\s*%",
    ]
    for pat in prob_pats:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            data.valuation_table.append(("Prob. of Positive Return", f"{m.group(1)}%"))
            break

    # CVaR / tail risk
    cvar_m = re.search(r"CVaR\s*[\(:=]\s*(-?\d+\.?\d*)\s*%", text, re.IGNORECASE)
    if cvar_m:
        data.valuation_table.append(("CVaR (95%)", f"{cvar_m.group(1)}%"))

    # ── Build financials table ───────────────────────────────────────────────
    _fin_context = {
        "Revenue Growth": "Year-over-year",
        "ROE": "Return on Equity",
        "Operating Margin": "Profitability",
        "P/E Ratio": "Price / Earnings",
        "Beta": "Market sensitivity",
        "Sharpe Ratio": "Risk-adjusted return",
        "RSI": "Momentum (14-day)",
        "Volatility": "Annualized",
        "Debt/Equity": "Leverage ratio",
        "Dividend Yield": "Annual yield",
        "EPS": "Earnings per share",
        "Current Ratio": "Liquidity",
        "Net Margin": "Net profitability",
    }
    existing_fin_metrics = {row[0] for row in data.financials}
    for label in ("Revenue Growth", "ROE", "Operating Margin", "P/E Ratio", "Beta", "Sharpe Ratio", "RSI", "Volatility",
                  "Debt/Equity", "Dividend Yield", "EPS", "Current Ratio", "Net Margin"):
        if label in extracted and label not in existing_fin_metrics:
            data.financials.append((label, extracted[label], _fin_context.get(label, "")))

    # ── Scorecard ────────────────────────────────────────────────────────────
    # Each entry: (dimension, [(pattern, group_index)], value_map)
    # Patterns try both "label adjective" and "adjective label" orders.
    _STRONG_MAP = {"strong": "strong", "solid": "strong", "robust": "strong",
                   "moderate": "moderate", "weak": "expensive", "poor": "expensive"}
    _VALUATION_MAP = {"expensive": "expensive", "rich": "expensive", "premium": "expensive",
                      "extreme": "expensive", "high": "expensive", "elevated": "expensive",
                      "cheap": "strong", "undervalued": "strong", "fair": "moderate",
                      "overvalued": "expensive"}
    _RISK_MAP = {"low": "strong", "moderate": "moderate",
                 "high": "expensive", "elevated": "expensive", "significant": "expensive"}
    _ANALYST_MAP = {"strong buy": "strong", "buy": "strong", "outperform": "strong",
                    "overweight": "strong", "hold": "bullish", "neutral": "moderate",
                    "sell": "expensive", "underweight": "expensive"}

    scorecard_entries: list[tuple[str, list[str], dict[str, str]]] = [
        ("Fundamentals", [
            r"(strong|weak|moderate|solid|robust)\s+(?:revenue\s+growth|fundamentals?|earnings)",
            r"fundamental[s]?\s*[:\s]?\s*(strong|weak|moderate|solid|robust)",
        ], _STRONG_MAP),
        ("Technical Outlook", [
            r"(strong\s+uptrend|uptrend|downtrend|golden\s+cross)\b",
            r"(?:technical[s]?|trend)\s*[:\s]?\s*(bullish|bearish|neutral|mixed)",
            r"(bullish|bearish|neutral|mixed)\s+(?:signals?|technicals?|momentum)",
        ], {"bullish": "bullish", "strong uptrend": "bullish", "uptrend": "bullish",
            "golden cross": "bullish", "bearish": "expensive", "downtrend": "expensive",
            "neutral": "moderate", "mixed": "moderate"}),
        ("Valuation", [
            r"(extreme|high|elevated|premium|rich|expensive)\s+valuation",
            r"valuation\s*[:\s]?\s*(expensive|cheap|fair|rich|premium|undervalued|overvalued|extreme|high|elevated)",
        ], _VALUATION_MAP),
        ("Risk Profile", [
            r"(significant|elevated|high)\s+(?:tail\s+)?risk",
            r"(?:risk|volatility|tail\s+risk)\s*[:\s]?\s*(low|moderate|high|elevated|significant)",
        ], _RISK_MAP),
        ("Profitability", [
            r"(robust|strong|high)\s+operating\s+margin",
            r"operating\s+margin\s*[\(:]\s*\d+",
            r"(?:profitability|margins?)\s*[:\s]?\s*(strong|weak|moderate|robust|high|improving)",
        ], {"strong": "strong", "robust": "strong", "high": "strong", "improving": "bullish",
            "moderate": "moderate", "weak": "expensive"}),
        ("Momentum", [
            r"RSI\s*[\(:=]\s*(\d+)",
        ], {"overbought": "expensive", "oversold": "strong"}),
        ("Analyst Sentiment", [
            r"""recommend[s]?\s+[\"']?(strong\s+buy|buy|hold|sell|outperform|overweight)[\"']?""",
            r"(?:analyst[s]?\s+(?:consensus|recommend|sentiment)|consensus)\s*[:\s]?\s*(strong\s+buy|buy|hold|sell|outperform|overweight|underweight|neutral)",
        ], _ANALYST_MAP),
    ]

    for dim, pats, mapping in scorecard_entries:
        for pat in pats:
            m = re.search(pat, text, re.IGNORECASE)
            if m:
                word = m.group(1).lower() if m.lastindex else ""
                badge = mapping.get(word, "moderate")
                # For "operating margin (65.6%)" — just mark as strong if margin > 20%
                if dim == "Profitability" and m.group(0) and "margin" in m.group(0).lower():
                    margin_m = re.search(r"operating\s+margin\s*[\(:]\s*(\d+\.?\d*)", text, re.IGNORECASE)
                    if margin_m and float(margin_m.group(1)) > 20:
                        word, badge = "strong", "strong"
                    elif margin_m and float(margin_m.group(1)) > 10:
                        word, badge = "moderate", "moderate"
                elif dim == "Momentum":
                    rsi_val = float(m.group(1))
                    if rsi_val > 70:
                        word, badge = "Overbought", "expensive"
                    elif rsi_val >= 50:
                        word, badge = "Bullish", "bullish"
                    elif rsi_val >= 30:
                        word, badge = "Neutral", "moderate"
                    else:
                        word, badge = "Oversold", "strong"
                data.scorecard.append((dim, word.capitalize(), badge))
                break
    data.scorecard.append(("Recommendation", data.recommendation,
                           "strong" if data.recommendation == "BUY"
                           else "bullish" if data.recommendation == "HOLD"
                           else "expensive"))

    # ── Risks and opportunities ──────────────────────────────────────────────
    # From parsed sections
    for sec in sections:
        lower_title = sec.title.lower()
        if any(k in lower_title for k in ("risk", "threat", "concern", "challenge")):
            data.risks.extend(_extract_bullets(sec.body)[:5])
        elif any(k in lower_title for k in ("opportunit", "catalyst", "growth", "strength", "upside")):
            data.opportunities.extend(_extract_bullets(sec.body)[:5])

    # From labelled blocks in text: "Key Risks to Monitor:\n" with per-line items
    if not data.risks:
        risk_block = re.search(
            r"(?:key\s+risks?\s*(?:to\s+monitor)?|risk\s+factors?)\s*:\s*\n((?:.*\n)*?)(?:\n\n|\nnext\s+step|\Z)",
            text, re.IGNORECASE,
        )
        if risk_block:
            data.risks = _extract_bullets(risk_block.group(1))[:5]

    # Inline comma-separated risks: "Key Risks: X, Y, and Z."
    if not data.risks:
        inline_risk = re.search(
            r"key\s+risks?\s*:\s*(.+?)(?:\.\s*$|\n\n|\n[A-Z])",
            text, re.IGNORECASE | re.MULTILINE,
        )
        if inline_risk:
            items = re.split(r",\s*(?:and\s+)?", inline_risk.group(1))
            data.risks = [i.strip().rstrip(".") for i in items if len(i.strip()) > 5][:5]

    # Bull Case / Bear Case — single paragraph on one line or multi-line block
    if not data.opportunities:
        bull_para = re.search(
            r"bull\s+case\s*:\s*(.+?)(?:\n(?:bear\s+case|confidence|next\s+step|key\s+risk)|\Z)",
            text, re.IGNORECASE | re.DOTALL,
        )
        if bull_para:
            raw = bull_para.group(1).strip()
            # Split on sentence boundaries
            parts = re.split(r"(?<=\.)\s+", raw)
            data.opportunities = [
                p.strip().rstrip(".") for p in parts
                if len(p.strip()) > 15
            ][:5]

    if not data.risks:
        bear_para = re.search(
            r"bear\s+case\s*:\s*(.+?)(?:\n(?:confidence|next\s+step|bull\s+case|key\s+risk)|\Z)",
            text, re.IGNORECASE | re.DOTALL,
        )
        if bear_para:
            raw = bear_para.group(1).strip()
            parts = re.split(r"(?<=\.)\s+", raw)
            data.risks = [
                p.strip().rstrip(".") for p in parts
                if len(p.strip()) > 15
            ][:5]

    # Growth opportunities / catalysts block with bullets
    if not data.opportunities:
        opp_block = re.search(
            r"(?:growth\s+(?:opportunities|drivers)|catalysts?)\s*:\s*\n((?:[\s\S]*?)(?=\n\n|\n[A-Z][a-z]|\Z))",
            text, re.IGNORECASE,
        )
        if opp_block:
            data.opportunities = _extract_bullets(opp_block.group(1))[:5]

    if not data.risks:
        data.risks = ["Market volatility", "Regulatory changes"]
    if not data.opportunities:
        data.opportunities = ["Strong operational execution", "Market positioning"]

    # ── Extract peer tickers from narrative text ─────────────────────────────
    if not data.peer_names:
        peer_pattern = re.compile(r"([A-Z][A-Za-z\s]+?)\s*\(([A-Z]{2,5})\)")
        for m in peer_pattern.finditer(text):
            sym = m.group(2)
            if sym != data.ticker and sym not in data.peer_names:
                data.peer_names.append(sym)
                if len(data.peer_names) >= 2:
                    break

    # ── Executive summary ────────────────────────────────────────────────────
    # Build a concise synthesized summary from extracted data
    summary_parts: list[str] = []

    # Lead with key fundamentals
    fund_metrics = []
    for label in ("Revenue Growth", "ROE", "Operating Margin"):
        if label in extracted:
            fund_metrics.append(f"{label.lower()} of {extracted[label]}")
    if fund_metrics:
        summary_parts.append(
            f"{data.company_name} shows strong fundamentals with {', '.join(fund_metrics)}"
        )

    # Add analyst target if available
    for vlabel, vval in data.valuation_table:
        if "target" in vlabel.lower():
            upside_str = ""
            for ul, uv in data.valuation_table:
                if "upside" in ul.lower():
                    upside_str = f" ({uv} upside)"
                    break
            summary_parts.append(f"Analyst consensus targets {vval}{upside_str}")
            break

    # Add a risk note if we have risks
    if data.risks and data.risks[0] != "Market volatility":
        summary_parts.append(f"Key risk: {data.risks[0].split('.')[0]}")

    if summary_parts:
        data.executive_summary = ". ".join(summary_parts) + "."
    else:
        # Fallback: extract from Bull Case or Synthesis block
        bull = re.search(
            r"(?:bull\s+case|synthesis|investment\s+thesis)\s*:\s*(.+?)(?:\n(?:bear\s+case|confidence|key\s+risk)|\Z)",
            text, re.IGNORECASE | re.DOTALL,
        )
        if bull:
            raw = bull.group(1).strip()
            first_sent = re.split(r"(?<=\.)\s+", raw)[0]
            data.executive_summary = _strip_markdown(first_sent[:600])
        else:
            lines = text.strip().split("\n")
            substance = []
            for line in lines:
                line = line.strip()
                if not line or line.startswith("Here is") or line.startswith("Investment Recommendation") or line.startswith("Confidence Score"):
                    continue
                substance.append(line)
                if len(" ".join(substance)) > 400:
                    break
            data.executive_summary = _strip_markdown(" ".join(substance)[:600])


# ── PPTX slide generators ──────────────────────────────────────────────────────

def _pptx_slide_title(deck: DeckData, h: SimpleNamespace) -> None:
    s = h.add_slide(dark=True)
    h.slide_label(s, "EQUITY RESEARCH REPORT", light=True)
    h.text(s, 0.83, 1.2, 10, 1.0, deck.company_name, 52, bold=True, color=_WHITE, font=h.FONT)
    exchange_label = f"NYSE: {deck.ticker}" if not deck.exchange else f"{deck.exchange}: {deck.ticker}"
    sector_label = f" · {deck.sector}" if deck.sector else ""
    date_label = f" · {deck.analysis_date}" if deck.analysis_date else ""
    h.text(s, 0.83, 2.1, 10, 0.4, f"{exchange_label}{sector_label}{date_label}", 18, color=_TEXT_LIGHT, font=h.FONT)
    kpi_y = 5.5
    h.text(s, 0.83, kpi_y, 2, 0.2, "Recommendation", 10, color=_TEXT_LIGHT, font=h.FONT, bold=True)
    rec_color = _BLUE if deck.recommendation == "HOLD" else _GREEN if deck.recommendation == "BUY" else _RED
    h.text(s, 0.83, kpi_y + 0.25, 2, 0.45, deck.recommendation, 28, bold=True, color=rec_color, font=h.MONO)
    h.text(s, 3.3, kpi_y, 2, 0.2, "Confidence", 10, color=_TEXT_LIGHT, font=h.FONT, bold=True)
    h.text(s, 3.3, kpi_y + 0.25, 2, 0.45, f"{deck.confidence:.0%}", 28, bold=True, color=_WHITE, font=h.MONO)
    if deck.scenarios.get("base"):
        h.text(s, 5.8, kpi_y, 2.5, 0.2, "Median Target", 10, color=_TEXT_LIGHT, font=h.FONT, bold=True)
        h.text(s, 5.8, kpi_y + 0.25, 2.5, 0.45, deck.scenarios["base"], 28, bold=True, color=_WHITE, font=h.MONO)
    h.footer(s, dark=True)


def _pptx_slide_key_metrics(deck: DeckData, h: SimpleNamespace) -> None:
    if not deck.kpi_chips:
        return
    s = h.add_slide()
    h.slide_label(s, "KEY METRICS")
    h.slide_title(s, "Performance Snapshot")
    chips = deck.kpi_chips[:4]
    n = len(chips)
    chip_w = {1: 5.0, 2: 4.0, 3: 3.3, 4: 2.7}.get(n, 2.7)
    gap = 0.3
    total_w = n * chip_w + (n - 1) * gap
    start_x = (13.33 - total_w) / 2
    for i, chip in enumerate(chips):
        x = start_x + i * (chip_w + gap)
        h.kpi_chip(s, x, 2.4, chip_w, chip["label"], chip["value"],
                   chip.get("context", ""), chip.get("positive", True))
    h.footer(s)


def _pptx_slide_thesis(deck: DeckData, h: SimpleNamespace) -> None:
    if not deck.executive_summary:
        return
    s = h.add_slide()
    h.slide_label(s, "INVESTMENT THESIS")
    h.slide_title(s, "Executive Summary")
    thesis_top = 2.6
    thesis_h = 3.5
    border = s.shapes.add_shape(1, h.Inches(0.83), h.Inches(thesis_top), h.Inches(0.04), h.Inches(thesis_h))
    border.fill.solid()
    border.fill.fore_color.rgb = h.rgb(_BLUE)
    border.line.fill.background()
    h.rounded_rect(s, 0.87, thesis_top, 11.5, thesis_h, _SURFACE)
    h.text(s, 1.2, thesis_top + 0.3, 10.8, thesis_h - 0.6, deck.executive_summary, 16, color=_TEXT, font=h.FONT)
    h.footer(s)


def _pptx_slide_financials(deck: DeckData, h: SimpleNamespace) -> None:
    if not deck.financials:
        return
    s = h.add_slide()
    h.slide_label(s, "FINANCIAL PERFORMANCE")
    h.slide_title(s, "Earnings & Growth")
    rows = deck.financials[:8]
    tbl_shape = s.shapes.add_table(
        len(rows) + 1, 3,
        h.Inches(0.83), h.Inches(2.4), h.Inches(11.5), h.Inches(min(4.2, 0.55 + len(rows) * 0.52)),
    )
    tbl = tbl_shape.table
    tbl.columns[0].width = h.Inches(5)
    tbl.columns[1].width = h.Inches(3.25)
    tbl.columns[2].width = h.Inches(3.25)
    for ci, hdr in enumerate(["METRIC", "CURRENT", "CONTEXT"]):
        cell = tbl.cell(0, ci)
        cell.fill.solid()
        cell.fill.fore_color.rgb = h.rgb(_WHITE)
        p = cell.text_frame.paragraphs[0]
        run = p.add_run()
        run.text = hdr
        run.font.bold = True
        run.font.size = h.Pt(10)
        run.font.color.rgb = h.rgb(_TEXT_LIGHT)
        run.font.name = h.FONT
        cell.margin_top = h.Pt(8)
        cell.margin_bottom = h.Pt(8)
        cell.margin_left = h.Pt(16)
    for ri, (metric, current, context) in enumerate(rows):
        for ci, (txt, is_metric) in enumerate([(metric, True), (current, False), (context, False)]):
            cell = tbl.cell(ri + 1, ci)
            cell.fill.solid()
            cell.fill.fore_color.rgb = h.rgb(_WHITE)
            p = cell.text_frame.paragraphs[0]
            run = p.add_run()
            run.text = txt
            run.font.size = h.Pt(14)
            run.font.name = h.MONO if not is_metric else h.FONT
            run.font.bold = is_metric
            run.font.color.rgb = h.rgb(_TEXT if is_metric else _GREEN_DARK if txt.startswith("+") else _TEXT)
            cell.margin_top = h.Pt(12)
            cell.margin_bottom = h.Pt(12)
            cell.margin_left = h.Pt(16)
    h.footer(s)


def _pptx_slide_valuation(deck: DeckData, h: SimpleNamespace) -> None:
    if not deck.valuation_table and not deck.scenarios:
        return
    s = h.add_slide()
    h.slide_label(s, "VALUATION")
    h.slide_title(s, "Scenario Analysis")
    if deck.valuation_table:
        vtbl_rows = deck.valuation_table[:6]
        vtbl_shape = s.shapes.add_table(
            len(vtbl_rows) + 1, 2,
            h.Inches(0.83), h.Inches(2.4), h.Inches(5.5), h.Inches(min(4.0, 0.55 + len(vtbl_rows) * 0.52)),
        )
        vtbl = vtbl_shape.table
        vtbl.columns[0].width = h.Inches(3)
        vtbl.columns[1].width = h.Inches(2.5)
        for ci, hdr in enumerate(["METRIC", "VALUE"]):
            cell = vtbl.cell(0, ci)
            cell.fill.solid()
            cell.fill.fore_color.rgb = h.rgb(_WHITE)
            p = cell.text_frame.paragraphs[0]
            run = p.add_run()
            run.text = hdr
            run.font.bold = True
            run.font.size = h.Pt(10)
            run.font.color.rgb = h.rgb(_TEXT_LIGHT)
            run.font.name = h.FONT
            cell.margin_left = h.Pt(16)
        for ri, (metric, value) in enumerate(vtbl_rows):
            for ci, (txt, is_metric) in enumerate([(metric, True), (value, False)]):
                cell = vtbl.cell(ri + 1, ci)
                cell.fill.solid()
                cell.fill.fore_color.rgb = h.rgb(_WHITE)
                p = cell.text_frame.paragraphs[0]
                run = p.add_run()
                run.text = txt
                run.font.size = h.Pt(13)
                run.font.name = h.MONO if not is_metric else h.FONT
                run.font.bold = is_metric
                val_color = _GREEN_DARK if txt.startswith("+") else _TEXT
                run.font.color.rgb = h.rgb(_TEXT if is_metric else val_color)
                cell.margin_top = h.Pt(10)
                cell.margin_bottom = h.Pt(10)
                cell.margin_left = h.Pt(16)
    card_x = 7.0
    card_w = 5.5
    card_h = 0.95
    scenario_list = []
    if deck.scenarios.get("bull"):
        scenario_list.append(("Bull Case", deck.scenarios["bull"], _GREEN_DARK))
    if deck.scenarios.get("base"):
        scenario_list.append(("Base Case", deck.scenarios["base"], _BLUE))
    if deck.scenarios.get("dcf"):
        scenario_list.append(("DCF Fair Value", deck.scenarios["dcf"], _AMBER))
    for i, (label, value, color) in enumerate(scenario_list):
        cy = 2.4 + i * (card_h + 0.2)
        h.rounded_rect(s, card_x, cy, card_w, card_h, _SURFACE)
        h.text(s, card_x + 0.3, cy + 0.12, card_w - 0.6, 0.2, label.upper(), 10, color=_TEXT_LIGHT, font=h.FONT, bold=True)
        h.text(s, card_x + 0.3, cy + 0.38, card_w - 0.6, 0.45, value, 28, bold=True, color=color, font=h.MONO)
    h.footer(s)


def _pptx_slide_scorecard(deck: DeckData, h: SimpleNamespace) -> None:
    if len(deck.scorecard) <= 1:
        return
    s = h.add_slide()
    h.slide_label(s, "ASSESSMENT")
    h.slide_title(s, "Investment Scorecard")
    badge_colors = {
        "strong": (_BADGE_STRONG_FG, _BADGE_STRONG_BG),
        "bullish": (_BADGE_BULLISH_FG, _BADGE_BULLISH_BG),
        "expensive": (_BADGE_EXPENSIVE_FG, _BADGE_EXPENSIVE_BG),
        "moderate": (_BADGE_MODERATE_FG, _BADGE_MODERATE_BG),
    }
    items = deck.scorecard[:6]
    n_items = len(items)
    if n_items <= 3:
        cols = n_items
    elif n_items == 4:
        cols = 2
    else:
        cols = 3
    card_w = 3.5
    card_h = 1.2
    gap_x = 0.35
    gap_y = 0.25
    total_w = cols * card_w + (cols - 1) * gap_x
    start_x = (13.33 - total_w) / 2
    start_y = 2.4
    for i, (dim, rating, badge_type) in enumerate(items):
        col = i % cols
        row = i // cols
        cx = start_x + col * (card_w + gap_x)
        cy = start_y + row * (card_h + gap_y)
        h.rounded_rect(s, cx, cy, card_w, card_h, _SURFACE)
        h.text(s, cx + 0.22, cy + 0.18, card_w - 0.4, 0.2, dim, 11, color=_TEXT_MID, font=h.FONT, bold=True)
        fg, bg = badge_colors.get(badge_type, badge_colors["moderate"])
        h.rounded_rect(s, cx + 0.22, cy + 0.55, 1.4, 0.38, bg)
        h.text(s, cx + 0.22, cy + 0.55, 1.4, 0.38, rating, 12, bold=True, color=fg, font=h.FONT,
               align=h.PP_ALIGN.CENTER, anchor=h.MSO_ANCHOR.MIDDLE)
    h.footer(s)


def _pptx_slide_peers(deck: DeckData, h: SimpleNamespace) -> None:
    if not deck.peers or not deck.peer_names:
        return
    s = h.add_slide()
    h.slide_label(s, "COMPETITIVE LANDSCAPE")
    h.slide_title(s, "Peer Comparison")
    headers = ["METRIC", deck.ticker] + deck.peer_names[:2]
    n_cols = len(headers)
    ptbl_shape = s.shapes.add_table(
        len(deck.peers) + 1, n_cols,
        h.Inches(0.83), h.Inches(2.4), h.Inches(11.5), h.Inches(min(4.2, 0.55 + len(deck.peers) * 0.52)),
    )
    ptbl = ptbl_shape.table
    col_w = 11.5 / n_cols
    for ci in range(n_cols):
        ptbl.columns[ci].width = h.Inches(col_w if ci > 0 else col_w * 1.3)
    for ci, hdr in enumerate(headers):
        cell = ptbl.cell(0, ci)
        cell.fill.solid()
        cell.fill.fore_color.rgb = h.rgb(_WHITE)
        p = cell.text_frame.paragraphs[0]
        p.alignment = h.PP_ALIGN.CENTER if ci > 0 else h.PP_ALIGN.LEFT
        run = p.add_run()
        run.text = hdr
        run.font.bold = True
        run.font.size = h.Pt(10)
        run.font.color.rgb = h.rgb(_TEXT_LIGHT)
        run.font.name = h.FONT
        cell.margin_left = h.Pt(16)
    for ri, peer_row in enumerate(deck.peers[:6]):
        values = [peer_row.get("metric", "")] + [peer_row.get(f"col{ci}", "N/A") for ci in range(n_cols - 1)]
        is_highlight = ri % 2 == 0
        for ci, txt in enumerate(values):
            cell = ptbl.cell(ri + 1, ci)
            cell.fill.solid()
            cell.fill.fore_color.rgb = h.rgb(_BLUE_LIGHT if is_highlight else _WHITE)
            p = cell.text_frame.paragraphs[0]
            p.alignment = h.PP_ALIGN.CENTER if ci > 0 else h.PP_ALIGN.LEFT
            run = p.add_run()
            run.text = str(txt)
            run.font.size = h.Pt(13)
            run.font.name = h.MONO if ci > 0 else h.FONT
            run.font.bold = ci == 0 or (ci == 1 and is_highlight)
            run.font.color.rgb = h.rgb(_TEXT if txt != "N/A" else _TEXT_LIGHT)
            cell.margin_top = h.Pt(10)
            cell.margin_bottom = h.Pt(10)
            cell.margin_left = h.Pt(16)
    h.footer(s)


def _pptx_slide_risk_reward(deck: DeckData, h: SimpleNamespace) -> None:
    if not deck.opportunities and not deck.risks:
        return
    s = h.add_slide()
    h.slide_label(s, "RISK–REWARD")
    h.slide_title(s, "Assessment")
    col_w = 5.5
    gap = 0.5
    total = 2 * col_w + gap
    sx = (13.33 - total) / 2
    n_items = max(len(deck.opportunities[:5]), len(deck.risks[:5]), 1)
    item_h = 0.7
    col_h = 0.9 + n_items * item_h
    opp_shape = s.shapes.add_shape(
        h.MSO_SHAPE.ROUNDED_RECTANGLE, h.Inches(sx), h.Inches(2.4), h.Inches(col_w), h.Inches(col_h),
    )
    opp_shape.fill.solid()
    opp_shape.fill.fore_color.rgb = h.rgb(_OPP_BG)
    opp_shape.line.color.rgb = h.rgb(_OPP_BORDER)
    opp_shape.line.width = h.Pt(1.5)
    h.text(s, sx + 0.3, 2.6, col_w - 0.6, 0.35, "Growth Opportunities", 16, bold=True, color=_GREEN_DARK, font=h.FONT)
    for i, opp in enumerate(deck.opportunities[:5]):
        opp_text = (opp[:117] + "...") if len(opp) > 120 else opp
        bullet_y = 3.15 + i * item_h
        dot = s.shapes.add_shape(
            h.MSO_SHAPE.OVAL, h.Inches(sx + 0.4), h.Inches(bullet_y + 0.06), h.Inches(0.08), h.Inches(0.08),
        )
        dot.fill.solid()
        dot.fill.fore_color.rgb = h.rgb(_GREEN)
        dot.line.fill.background()
        h.text(s, sx + 0.65, bullet_y, col_w - 1.0, item_h, opp_text, 12, color=_TEXT, font=h.FONT)
    rx = sx + col_w + gap
    risk_shape = s.shapes.add_shape(
        h.MSO_SHAPE.ROUNDED_RECTANGLE, h.Inches(rx), h.Inches(2.4), h.Inches(col_w), h.Inches(col_h),
    )
    risk_shape.fill.solid()
    risk_shape.fill.fore_color.rgb = h.rgb(_RISK_BG)
    risk_shape.line.color.rgb = h.rgb(_RISK_BORDER)
    risk_shape.line.width = h.Pt(1.5)
    h.text(s, rx + 0.3, 2.6, col_w - 0.6, 0.35, "Key Risks", 16, bold=True, color=_RED, font=h.FONT)
    for i, risk in enumerate(deck.risks[:5]):
        risk_text = (risk[:117] + "...") if len(risk) > 120 else risk
        bullet_y = 3.15 + i * item_h
        dot = s.shapes.add_shape(
            h.MSO_SHAPE.OVAL, h.Inches(rx + 0.4), h.Inches(bullet_y + 0.06), h.Inches(0.08), h.Inches(0.08),
        )
        dot.fill.solid()
        dot.fill.fore_color.rgb = h.rgb(_RED)
        dot.line.fill.background()
        h.text(s, rx + 0.65, bullet_y, col_w - 1.0, item_h, risk_text, 12, color=_TEXT, font=h.FONT)
    h.footer(s)


def _pptx_slide_extra(deck: DeckData, h: SimpleNamespace, section: Section) -> None:
    if not section.body:
        return
    body = section.body
    chunks: list[str] = []
    while len(body) > _MAX_SLIDE_CHARS:
        split_at = body.rfind("\n", 0, _MAX_SLIDE_CHARS)
        if split_at < 0:
            split_at = _MAX_SLIDE_CHARS
        chunks.append(body[:split_at])
        body = body[split_at:].strip()
    chunks.append(body)
    for ci, chunk in enumerate(chunks):
        sld = h.add_slide()
        label_text = section.title.upper()
        h.slide_label(sld, label_text if ci == 0 else f"{label_text} (CONT.)")
        h.slide_title(sld, section.title if ci == 0 else f"{section.title} (cont.)")
        border = sld.shapes.add_shape(1, h.Inches(0.83), h.Inches(2.5), h.Inches(0.04), h.Inches(4.0))
        border.fill.solid()
        border.fill.fore_color.rgb = h.rgb(_BLUE)
        border.line.fill.background()
        h.rounded_rect(sld, 0.87, 2.5, 11.5, 4.0, _SURFACE)
        h.text(sld, 1.2, 2.7, 10.8, 3.6, chunk, 14, color=_TEXT, font=h.FONT)
        h.footer(sld)


def _pptx_slide_conclusion(deck: DeckData, h: SimpleNamespace) -> None:
    s = h.add_slide(dark=True)
    h.slide_label(s, "CONCLUSION", left=0.83, top=2.0, light=True)
    div = s.shapes.add_shape(1, h.Inches(6.2), h.Inches(2.5), h.Inches(0.9), h.Inches(0.04))
    div.fill.solid()
    div.fill.fore_color.rgb = h.rgb(_BLUE)
    div.line.fill.background()
    h.text(s, 0, 2.8, 13.33, 0.7, deck.recommendation, 44, bold=True, color=_BLUE, font=h.MONO, align=h.PP_ALIGN.CENTER)
    h.text(s, 0, 3.5, 13.33, 0.4, f"{deck.confidence:.0%} Confidence", 14, color=_TEXT_LIGHT, font=h.FONT, align=h.PP_ALIGN.CENTER)
    conclusion_text = deck.executive_summary[:300] if deck.executive_summary else ""
    if conclusion_text:
        h.text(s, 2.5, 4.2, 8.33, 1.5, conclusion_text, 15, color=_TEXT_LIGHT, font=h.FONT, align=h.PP_ALIGN.CENTER)
    h.footer(s, dark=True)


# ── PPTX generation ───────────────────────────────────────────────────────────

def generate_pptx(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> BytesIO:
    from pptx import Presentation
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
    from pptx.enum.shapes import MSO_SHAPE
    from pptx.util import Inches, Pt, Emu

    def rgb(hex_str: str) -> RGBColor:
        return RGBColor.from_string(hex_str)

    deck = _extract_deck_data(brief_data, ticker, recommendation, confidence, analysis_date)
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)
    blank_layout = prs.slide_layouts[6]

    FONT = "Calibri"
    MONO = "Consolas"

    def add_slide(dark: bool = False):
        sld = prs.slides.add_slide(blank_layout)
        bg = sld.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(7.5))
        bg.fill.solid()
        bg.fill.fore_color.rgb = rgb(_NAVY if dark else _WHITE)
        bg.line.fill.background()
        return sld

    def _text(slide, left, top, width, height, text, size,
              bold=False, color=_TEXT, align=PP_ALIGN.LEFT, font=FONT,
              wrap=True, anchor=MSO_ANCHOR.TOP):
        box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = box.text_frame
        tf.word_wrap = wrap
        tf.auto_size = None
        try:
            tf.vertical_anchor = anchor
        except Exception:
            pass
        p = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = rgb(color)
        run.font.name = font
        return box

    def _multiline(slide, left, top, width, height, lines, size,
                   color=_TEXT, font=FONT, line_spacing=1.5):
        box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = box.text_frame
        tf.word_wrap = True
        for i, line_text in enumerate(lines):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.space_after = Pt(4)
            run = p.add_run()
            run.text = line_text
            run.font.size = Pt(size)
            run.font.color.rgb = rgb(color)
            run.font.name = font
        return box

    def _rounded_rect(slide, left, top, width, height, fill_color, border_color=None):
        shape = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE,
            Inches(left), Inches(top), Inches(width), Inches(height),
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = rgb(fill_color)
        if border_color:
            shape.line.color.rgb = rgb(border_color)
            shape.line.width = Pt(1.5)
        else:
            shape.line.fill.background()
        return shape

    def _slide_label(slide, text, left=0.83, top=0.7, light=False):
        _text(slide, left, top, 4, 0.25, text, 11,
              bold=True, color=_TEXT_LIGHT if light else _BLUE, font=FONT)

    def _slide_title(slide, text, left=0.83, top=0.95, light=False):
        _text(slide, left, top, 10, 0.7, text, 36,
              bold=True, color=_WHITE if light else _TEXT, font=FONT)

    def _footer(slide, dark=False):
        color = _TEXT_LIGHT if not dark else _TEXT_MID
        _text(slide, 0.83, 7.0, 5, 0.3,
              "© 2026 Institutional Equity Research", 9, color=color)
        _text(slide, 7, 7.0, 5.5, 0.3,
              "For informational purposes only", 9, color=color, align=PP_ALIGN.RIGHT)

    def _kpi_chip(slide, left, top, width, label, value, context="",
                  positive=True, dark=False):
        chip_bg = _NAVY_MID if dark else _SURFACE
        _rounded_rect(slide, left, top, width, 1.2, chip_bg)
        _text(slide, left + 0.22, top + 0.2, width - 0.4, 0.25, label, 11,
              color=_TEXT_MID if not dark else _TEXT_LIGHT, font=FONT, bold=True)
        val_color = _GREEN_DARK if positive else _RED
        if not positive and value.startswith("-"):
            val_color = _RED
        _text(slide, left + 0.22, top + 0.5, width - 0.4, 0.45, value, 30,
              bold=True, color=val_color, font=MONO)
        if context:
            _text(slide, left + 0.22, top + 0.92, width - 0.4, 0.2, context, 10, color=_TEXT_LIGHT)

    h = SimpleNamespace(
        add_slide=add_slide,
        text=_text,
        multiline=_multiline,
        rounded_rect=_rounded_rect,
        kpi_chip=_kpi_chip,
        slide_label=_slide_label,
        slide_title=_slide_title,
        footer=_footer,
        rgb=rgb,
        FONT=FONT, MONO=MONO,
        Inches=Inches, Pt=Pt, Emu=Emu,
        PP_ALIGN=PP_ALIGN, MSO_ANCHOR=MSO_ANCHOR, MSO_SHAPE=MSO_SHAPE,
        blank_layout=blank_layout,
        prs=prs,
    )

    _pptx_slide_title(deck, h)
    _pptx_slide_key_metrics(deck, h)
    _pptx_slide_thesis(deck, h)
    _pptx_slide_financials(deck, h)
    _pptx_slide_valuation(deck, h)
    _pptx_slide_scorecard(deck, h)
    _pptx_slide_peers(deck, h)
    _pptx_slide_risk_reward(deck, h)
    for section in deck.sections[:4]:
        _pptx_slide_extra(deck, h, section)
    _pptx_slide_conclusion(deck, h)

    buf = BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf


# ── DOCX generation ───────────────────────────────────────────────────────────

def _extract_docx_content(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> DeckData:
    """Wrapper for DOCX — reuses the deck extractor."""
    return _extract_deck_data(brief_data, ticker, recommendation, confidence, analysis_date)


def generate_docx(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> BytesIO:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    def rgb(hex_str: str) -> RGBColor:
        r = int(hex_str[0:2], 16)
        g = int(hex_str[2:4], 16)
        b = int(hex_str[4:6], 16)
        return RGBColor(r, g, b)

    deck = _extract_docx_content(brief_data, ticker, recommendation, confidence, analysis_date)
    doc = Document()

    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    def set_run_style(run, size: int, bold: bool = False,
                      color: str = _TEXT, italic: bool = False, name: str = "Calibri") -> None:
        run.font.name = name
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.italic = italic
        run.font.color.rgb = rgb(color)

    # ── Document title block ──────────────────────────────────────────────────
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_p.add_run("Investment Analysis Report")
    set_run_style(run, 28, bold=True, color=_DOCX_NAVY)

    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub_p.add_run(ticker)
    set_run_style(run, 22, bold=True, color=_DOCX_BLUE)

    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta_p.add_run(f"{analysis_date}  ·  Confidence: {confidence:.0%}")
    set_run_style(run, 11, color=_TEXT_LIGHT)

    sig_p = doc.add_paragraph()
    sig_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fg, _ = _SIGNAL_COLOURS.get(deck.recommendation, (_TEXT, _SURFACE))
    run = sig_p.add_run(f"  {deck.recommendation}  ")
    set_run_style(run, 14, bold=True, color=fg)

    doc.add_paragraph()

    # ── Executive Summary ─────────────────────────────────────────────────────
    if deck.executive_summary:
        h = doc.add_heading("Executive Summary", level=1)
        h.runs[0].font.color.rgb = rgb(_DOCX_NAVY)
        h.runs[0].font.name = "Calibri"

        para = doc.add_paragraph(deck.executive_summary)
        para.runs[0].font.size = Pt(11)
        para.runs[0].font.name = "Calibri"
        para.runs[0].font.color.rgb = rgb(_TEXT)
        para.paragraph_format.space_after = Pt(8)
        doc.add_paragraph()

    # ── Key Metrics table ─────────────────────────────────────────────────────
    if deck.kpi_chips:
        h = doc.add_heading("Key Metrics", level=1)
        h.runs[0].font.color.rgb = rgb(_DOCX_NAVY)
        h.runs[0].font.name = "Calibri"

        items = [(c["label"], c["value"]) for c in deck.kpi_chips]
        tbl = doc.add_table(rows=len(items) + 1, cols=2)
        tbl.style = "Table Grid"
        hdr_cells = tbl.rows[0].cells
        for ci, txt in enumerate(["Metric", "Value"]):
            hdr_cells[ci].text = txt
            run = hdr_cells[ci].paragraphs[0].runs[0]
            run.font.bold = True
            run.font.size = Pt(10)
            run.font.name = "Calibri"
            run.font.color.rgb = rgb(_WHITE)
            tc = hdr_cells[ci]._tc
            tcPr = tc.get_or_add_tcPr()
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), _DOCX_BLUE)
            tcPr.append(shd)

        for ri, (label, value) in enumerate(items):
            row_cells = tbl.rows[ri + 1].cells
            row_cells[0].text = label
            row_cells[1].text = value
            for cell in row_cells:
                r = cell.paragraphs[0].runs[0]
                r.font.size = Pt(10)
                r.font.name = "Calibri"
            row_cells[0].paragraphs[0].runs[0].font.bold = True
            row_cells[0].paragraphs[0].runs[0].font.color.rgb = rgb(_DOCX_NAVY)
            if ri % 2 == 0:
                for cell in row_cells:
                    tc = cell._tc
                    tcPr = tc.get_or_add_tcPr()
                    shd = OxmlElement("w:shd")
                    shd.set(qn("w:val"), "clear")
                    shd.set(qn("w:color"), "auto")
                    shd.set(qn("w:fill"), _DOCX_SURFACE)
                    tcPr.append(shd)

        doc.add_paragraph()

    # ── Analysis sections ─────────────────────────────────────────────────────
    for section in deck.sections:
        if not section.title and not section.body:
            continue
        if section.title:
            h = doc.add_heading(section.title, level=2)
            for run in h.runs:
                run.font.color.rgb = rgb(_DOCX_BLUE)
                run.font.name = "Calibri"
        if section.body:
            for block in section.body.split("\n\n"):
                block = block.strip()
                if not block:
                    continue
                if block.startswith("•"):
                    for line in block.split("\n"):
                        line = line.strip().lstrip("•").strip()
                        if line:
                            para = doc.add_paragraph(line, style="List Bullet")
                            if para.runs:
                                para.runs[0].font.size = Pt(11)
                                para.runs[0].font.name = "Calibri"
                else:
                    para = doc.add_paragraph(block)
                    if para.runs:
                        para.runs[0].font.size = Pt(11)
                        para.runs[0].font.name = "Calibri"
                        para.runs[0].font.color.rgb = rgb(_TEXT)
                    para.paragraph_format.space_after = Pt(6)
        doc.add_paragraph()

    # ── Risk / Opportunities ──────────────────────────────────────────────────
    if deck.opportunities or deck.risks:
        if deck.opportunities:
            h = doc.add_heading("Growth Opportunities", level=2)
            for run in h.runs:
                run.font.color.rgb = rgb(_GREEN_DARK)
                run.font.name = "Calibri"
            for opp in deck.opportunities:
                para = doc.add_paragraph(opp, style="List Bullet")
                if para.runs:
                    para.runs[0].font.size = Pt(11)
                    para.runs[0].font.name = "Calibri"

        if deck.risks:
            h = doc.add_heading("Key Risks", level=2)
            for run in h.runs:
                run.font.color.rgb = rgb(_RED)
                run.font.name = "Calibri"
            for risk in deck.risks:
                para = doc.add_paragraph(risk, style="List Bullet")
                if para.runs:
                    para.runs[0].font.size = Pt(11)
                    para.runs[0].font.name = "Calibri"

        doc.add_paragraph()

    # ── Disclaimer ────────────────────────────────────────────────────────────
    doc.add_paragraph()
    h = doc.add_heading("Disclaimer", level=2)
    for run in h.runs:
        run.font.color.rgb = rgb(_DOCX_BLUE)
        run.font.name = "Calibri"
    para = doc.add_paragraph(deck.disclaimer)
    if para.runs:
        para.runs[0].font.size = Pt(9)
        para.runs[0].font.italic = True
        para.runs[0].font.color.rgb = rgb(_TEXT_LIGHT)
        para.runs[0].font.name = "Calibri"

    section_obj = doc.sections[0]
    footer = section_obj.footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run(f"Generated by FinSight  ·  {analysis_date}")
    run.font.size = Pt(8)
    run.font.color.rgb = rgb(_TEXT_LIGHT)
    run.font.name = "Calibri"

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


# ── Jinja2 HTML Generation ─────────────────────────────────────────────────────


def _deck_to_template_context(deck: DeckData) -> dict:
    """Build Jinja2 template context from DeckData."""
    rec_colors = {"BUY": "var(--green)", "HOLD": "var(--blue)", "SELL": "var(--red)"}
    confidence_pct = f"{deck.confidence:.0%}"

    scenario_cards = []
    if deck.scenarios.get("bull"):
        scenario_cards.append(("Bull Case", deck.scenarios["bull"], "var(--green-dark)"))
    if deck.scenarios.get("base"):
        scenario_cards.append(("Base Case", deck.scenarios["base"], "var(--blue)"))
    if deck.scenarios.get("dcf"):
        scenario_cards.append(("DCF Fair Value", deck.scenarios["dcf"], "var(--amber)"))

    return {
        "deck": deck,
        "rec_colors": rec_colors,
        "confidence_pct": confidence_pct,
        "scenario_cards": scenario_cards,
    }


_jinja_env: "jinja2.Environment | None" = None


def _get_jinja_env() -> "jinja2.Environment":
    global _jinja_env
    if _jinja_env is None:
        from pathlib import Path
        import jinja2
        template_dir = Path(__file__).parent / "templates"
        _jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(template_dir)),
            autoescape=True,
        )
    return _jinja_env


def generate_html(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> str:
    """Generate a standalone HTML investment deck. Returns HTML string."""
    deck = _extract_deck_data(brief_data, ticker, recommendation, confidence, analysis_date)
    ctx = _deck_to_template_context(deck)
    template = _get_jinja_env().get_template("investment_deck.html")
    return template.render(**ctx)
