"""Generate PPTX and DOCX investment reports from brief_json data.

Public API:
    generate_pptx(brief_data, ticker, recommendation, confidence, analysis_date) -> BytesIO
    generate_docx(brief_data, ticker, recommendation, confidence, analysis_date) -> BytesIO

Handles both brief_json shapes:
  - Full InvestmentBrief JSON (has rag_insights, quant_metrics, etc.)
  - Minimal {"response_text": "..."} (markdown text from LLM synthesis)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from io import BytesIO
from typing import Optional

# ── Colour palette matching FinSight brand ────────────────────────────────────
_CLAY_DEEP = "5C3D2E"
_CLAY = "9C6644"
_CLAY_LIGHT = "C8A882"
_IVORY = "FAFAF5"
_IVORY_DARK = "F3F1EA"
_SAND = "E2DDD3"
_TEXT = "2C2C2C"
_TEXT_MUTED = "8A8A7A"
_BUY_GREEN = "2E7D32"
_BUY_BG = "E8F5E9"
_HOLD_AMBER = "E68A00"
_HOLD_BG = "FFF8E1"
_SELL_RED = "C62828"
_SELL_BG = "FFEBEE"
_WHITE = "FFFFFF"

_SIGNAL_COLOURS = {
    "BUY": (_BUY_GREEN, _BUY_BG),
    "HOLD": (_HOLD_AMBER, _HOLD_BG),
    "SELL": (_SELL_RED, _SELL_BG),
}

_DEFAULT_DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It does not constitute financial advice. Past performance is not indicative of future results. "
    "Always consult a qualified financial advisor before making investment decisions."
)

_MAX_SLIDE_CHARS = 1200  # ~300 words per slide


# ── Parsed report structure ───────────────────────────────────────────────────

@dataclass
class Section:
    title: str
    body: str


@dataclass
class ReportContent:
    ticker: str
    recommendation: str
    confidence: float
    analysis_date: str
    executive_summary: str
    sections: list[Section] = field(default_factory=list)
    metrics: Optional[dict] = None  # flat key/value pairs for table
    disclaimer: str = _DEFAULT_DISCLAIMER


# ── Content extraction helpers ────────────────────────────────────────────────

def _strip_markdown(text: str) -> str:
    """Remove markdown syntax, keeping plain readable text."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    text = re.sub(r"^\|.+\|$", "", text, flags=re.MULTILINE)  # table rows
    text = re.sub(r"^[-|:]+$", "", text, flags=re.MULTILINE)  # table separators
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)  # inline headers
    text = re.sub(r"^[-*+]\s+", "• ", text, flags=re.MULTILINE)  # bullets
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _parse_markdown_sections(text: str) -> list[Section]:
    """Split markdown on ## headers into sections."""
    parts = re.split(r"\n##\s+", "\n" + text)
    sections: list[Section] = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        lines = part.split("\n", 1)
        title = _strip_markdown(lines[0].strip())
        body = _strip_markdown(lines[1].strip()) if len(lines) > 1 else ""
        if title and (body or title):
            sections.append(Section(title=title, body=body))
    return sections


def _extract_content(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> ReportContent:
    content = ReportContent(
        ticker=ticker,
        recommendation=recommendation.upper() if recommendation else "UNKNOWN",
        confidence=confidence,
        analysis_date=analysis_date,
        executive_summary="",
    )

    # ── Structured InvestmentBrief path ──────────────────────────────────────
    if "final_recommendation" in brief_data or "rag_insights" in brief_data:
        rationale = brief_data.get("recommendation_rationale", "")
        content.executive_summary = _strip_markdown(rationale[:600]) if rationale else ""

        # Build metrics table from quant + sentiment data
        metrics: dict[str, str] = {}
        qm = brief_data.get("quant_metrics", {})
        si = brief_data.get("sentiment_intelligence", {})
        ri = brief_data.get("rag_insights", {})

        if qm.get("sharpe_ratio") is not None:
            metrics["Sharpe Ratio"] = f"{qm['sharpe_ratio']:.2f}"
        if qm.get("annual_volatility") is not None:
            metrics["Annual Volatility"] = f"{qm['annual_volatility']*100:.1f}%"
        if qm.get("beta") is not None:
            metrics["Beta"] = f"{qm['beta']:.2f}"
        if qm.get("var_95_daily") is not None:
            metrics["VaR (95%, daily)"] = f"{qm['var_95_daily']*100:.2f}%"
        if qm.get("dcf_intrinsic_value"):
            metrics["DCF Intrinsic Value"] = f"${qm['dcf_intrinsic_value']:.2f}"
        if si.get("avg_price_target"):
            metrics["Analyst Price Target"] = f"${si['avg_price_target']:.2f}"
        if si.get("analyst_consensus"):
            metrics["Analyst Consensus"] = si["analyst_consensus"]
        if si.get("insider_signal"):
            metrics["Insider Signal"] = si["insider_signal"]
        if ri.get("revenue_growth_yoy") is not None:
            metrics["Revenue Growth YoY"] = f"{ri['revenue_growth_yoy']*100:.1f}%"
        if ri.get("confidence_score") is not None:
            metrics["RAG Confidence"] = f"{ri['confidence_score']:.2f}"

        content.metrics = metrics if metrics else None

        # Build sections from sub-agent data
        if ri:
            body_parts = []
            if ri.get("forward_guidance"):
                body_parts.append(f"Forward Guidance: {ri['forward_guidance']}")
            risks = ri.get("key_risks", [])
            if risks:
                body_parts.append("Key Risks:\n" + "\n".join(f"• {r}" for r in risks))
            if ri.get("cited_documents"):
                body_parts.append("Sources: " + ", ".join(ri["cited_documents"][:3]))
            content.sections.append(Section("Fundamental Analysis", "\n\n".join(body_parts)))

        if si:
            body_parts = []
            if si.get("narrative"):
                body_parts.append(si["narrative"])
            cats = si.get("key_catalysts", [])
            if cats:
                body_parts.append("Key Catalysts:\n" + "\n".join(f"• {c}" for c in cats))
            si_risks = si.get("key_risks", [])
            if si_risks:
                body_parts.append("Risks:\n" + "\n".join(f"• {r}" for r in si_risks))
            content.sections.append(Section("Market Sentiment", "\n\n".join(body_parts)))

        content.disclaimer = brief_data.get("disclaimer", _DEFAULT_DISCLAIMER)
        return content

    # ── Minimal response_text path ────────────────────────────────────────────
    response_text = brief_data.get("response_text", "")
    if not response_text:
        content.executive_summary = "No analysis content available."
        return content

    sections = _parse_markdown_sections(response_text)

    # First section (or first 600 chars if no headers) → executive summary
    if sections:
        first = sections[0]
        # Use first section as executive summary, remaining as body sections
        content.executive_summary = (first.body or first.title)[:600]
        content.sections = sections[1:]
    else:
        content.executive_summary = _strip_markdown(response_text[:600])

    return content


# ── PPTX generation ───────────────────────────────────────────────────────────

def generate_pptx(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> BytesIO:
    from pptx import Presentation
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    from pptx.util import Inches, Pt

    def rgb(hex_str: str) -> RGBColor:
        return RGBColor.from_string(hex_str)

    content = _extract_content(brief_data, ticker, recommendation, confidence, analysis_date)
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]  # completely blank

    def add_slide() -> object:
        return prs.slides.add_slide(blank_layout)

    def add_textbox(slide, left, top, width, height, text, font_size,
                    bold=False, color=_TEXT, align=PP_ALIGN.LEFT, wrap=True) -> object:
        from pptx.util import Inches, Pt
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = txBox.text_frame
        tf.word_wrap = wrap
        p = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size = Pt(font_size)
        run.font.bold = bold
        run.font.color.rgb = rgb(color)
        run.font.name = "Calibri"
        return txBox

    def add_footer(slide, date_str: str) -> None:
        add_textbox(
            slide, 0.3, 7.1, 12.7, 0.35,
            f"FinSight Investment Research  ·  {date_str}",
            8, color=_TEXT_MUTED, align=PP_ALIGN.CENTER,
        )

    def add_signal_badge(slide, signal: str) -> None:
        from pptx.util import Inches, Pt
        fg, bg = _SIGNAL_COLOURS.get(signal, (_TEXT, _IVORY_DARK))
        shape = slide.shapes.add_shape(
            1,  # MSO_SHAPE_TYPE.RECTANGLE
            Inches(0.5), Inches(2.3), Inches(1.4), Inches(0.5),
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = rgb(bg)
        shape.line.color.rgb = rgb(fg)
        shape.line.width = Pt(1.5)
        tf = shape.text_frame
        tf.paragraphs[0].alignment = PP_ALIGN.CENTER
        run = tf.paragraphs[0].add_run()
        run.text = signal
        run.font.bold = True
        run.font.size = Pt(14)
        run.font.color.rgb = rgb(fg)
        run.font.name = "Calibri"

    # ── Slide 1: Title ────────────────────────────────────────────────────────
    slide1 = add_slide()
    # Clay top bar
    bar = slide1.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.18))
    bar.fill.solid()
    bar.fill.fore_color.rgb = rgb(_CLAY)
    bar.line.fill.background()

    add_textbox(slide1, 0.5, 0.4, 12, 0.9, "FinSight Investment Research",
                11, color=_CLAY, bold=True)
    add_textbox(slide1, 0.5, 1.0, 10, 1.2,
                f"Investment Analysis: {ticker}",
                36, bold=True, color=_CLAY_DEEP)
    add_signal_badge(slide1, content.recommendation)
    add_textbox(slide1, 2.1, 2.3, 5, 0.5,
                f"Confidence: {content.confidence:.0%}  ·  {content.analysis_date}",
                13, color=_TEXT_MUTED)
    add_textbox(slide1, 0.5, 6.5, 12.3, 0.6,
                "For informational purposes only. Not financial advice.",
                9, color=_TEXT_MUTED)
    add_footer(slide1, content.analysis_date)

    # ── Slide 2: Executive Summary ────────────────────────────────────────────
    if content.executive_summary:
        slide2 = add_slide()
        bar2 = slide2.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.18))
        bar2.fill.solid()
        bar2.fill.fore_color.rgb = rgb(_CLAY)
        bar2.line.fill.background()
        add_textbox(slide2, 0.5, 0.35, 12, 0.55, "Executive Summary",
                    22, bold=True, color=_CLAY_DEEP)
        # Divider line
        line = slide2.shapes.add_shape(1, Inches(0.5), Inches(1.0), Inches(12.3), Inches(0.03))
        line.fill.solid()
        line.fill.fore_color.rgb = rgb(_SAND)
        line.line.fill.background()
        add_textbox(slide2, 0.5, 1.15, 12.3, 5.8,
                    content.executive_summary, 14, color=_TEXT)
        add_footer(slide2, content.analysis_date)

    # ── Slide 3: Key Metrics (structured briefs only) ─────────────────────────
    if content.metrics:
        slide3 = add_slide()
        bar3 = slide3.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.18))
        bar3.fill.solid()
        bar3.fill.fore_color.rgb = rgb(_CLAY)
        bar3.line.fill.background()
        add_textbox(slide3, 0.5, 0.35, 12, 0.55, "Key Metrics",
                    22, bold=True, color=_CLAY_DEEP)

        from pptx.util import Inches, Pt
        rows = list(content.metrics.items())
        # Build a 2-column wide table: label | value | label | value
        paired = []
        for i in range(0, len(rows), 2):
            left = rows[i]
            right = rows[i + 1] if i + 1 < len(rows) else ("", "")
            paired.append((left[0], left[1], right[0], right[1]))

        tbl = slide3.shapes.add_table(
            len(paired) + 1, 4,
            Inches(0.5), Inches(1.1), Inches(12.3), Inches(min(5.5, 0.5 + len(paired) * 0.52)),
        ).table
        # Header row
        for ci, hdr in enumerate(["Metric", "Value", "Metric", "Value"]):
            cell = tbl.cell(0, ci)
            cell.fill.solid()
            cell.fill.fore_color.rgb = rgb(_CLAY)
            p = cell.text_frame.paragraphs[0]
            run = p.add_run()
            run.text = hdr
            run.font.bold = True
            run.font.size = Pt(11)
            run.font.color.rgb = rgb(_WHITE)
            run.font.name = "Calibri"
        # Data rows
        for ri, (l1, v1, l2, v2) in enumerate(paired):
            for ci, txt in enumerate([l1, v1, l2, v2]):
                cell = tbl.cell(ri + 1, ci)
                if ri % 2 == 0:
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = rgb(_IVORY_DARK)
                p = cell.text_frame.paragraphs[0]
                run = p.add_run()
                run.text = txt
                run.font.size = Pt(11)
                run.font.bold = ci in (0, 2)
                run.font.color.rgb = rgb(_CLAY_DEEP if ci in (0, 2) else _TEXT)
                run.font.name = "Calibri"
        add_footer(slide3, content.analysis_date)

    # ── Analysis section slides ───────────────────────────────────────────────
    for section in content.sections:
        if not section.body and not section.title:
            continue
        # Split long sections across multiple slides
        body = section.body
        chunks: list[str] = []
        while len(body) > _MAX_SLIDE_CHARS:
            split_at = body.rfind("\n", 0, _MAX_SLIDE_CHARS)
            if split_at < 0:
                split_at = _MAX_SLIDE_CHARS
            chunks.append(body[:split_at])
            body = body[split_at:].strip()
        chunks.append(body)

        for ci, chunk in enumerate(chunks):
            sld = add_slide()
            bar_s = sld.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.18))
            bar_s.fill.solid()
            bar_s.fill.fore_color.rgb = rgb(_CLAY)
            bar_s.line.fill.background()
            title_text = section.title if ci == 0 else f"{section.title} (cont.)"
            add_textbox(sld, 0.5, 0.35, 12, 0.55, title_text,
                        22, bold=True, color=_CLAY_DEEP)
            ln = sld.shapes.add_shape(1, Inches(0.5), Inches(1.0), Inches(12.3), Inches(0.03))
            ln.fill.solid()
            ln.fill.fore_color.rgb = rgb(_SAND)
            ln.line.fill.background()
            add_textbox(sld, 0.5, 1.15, 12.3, 5.8, chunk, 13, color=_TEXT)
            add_footer(sld, content.analysis_date)

    # ── Final slide: Disclaimer ───────────────────────────────────────────────
    slide_d = add_slide()
    bar_d = slide_d.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.18))
    bar_d.fill.solid()
    bar_d.fill.fore_color.rgb = rgb(_CLAY)
    bar_d.line.fill.background()
    add_textbox(slide_d, 0.5, 0.35, 12, 0.55, "Disclaimer",
                22, bold=True, color=_CLAY_DEEP)
    add_textbox(slide_d, 0.5, 1.15, 12.3, 5.0, content.disclaimer,
                12, color=_TEXT_MUTED)
    add_footer(slide_d, content.analysis_date)

    buf = BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf


# ── DOCX generation ───────────────────────────────────────────────────────────

def generate_docx(
    brief_data: dict,
    ticker: str,
    recommendation: str,
    confidence: float,
    analysis_date: str,
) -> BytesIO:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    def rgb(hex_str: str) -> RGBColor:
        r = int(hex_str[0:2], 16)
        g = int(hex_str[2:4], 16)
        b = int(hex_str[4:6], 16)
        return RGBColor(r, g, b)

    content = _extract_content(brief_data, ticker, recommendation, confidence, analysis_date)
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    def set_run_style(run, size: int, bold: bool = False,
                      color: str = _TEXT, italic: bool = False, name: str = "Calibri") -> None:
        run.font.name = name
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.italic = italic
        run.font.color.rgb = rgb(color)

    # ── Document title block ──────────────────────────────────────────────────
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_p.add_run("Investment Analysis Report")
    set_run_style(run, 28, bold=True, color=_CLAY_DEEP)

    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub_p.add_run(ticker)
    set_run_style(run, 22, bold=True, color=_CLAY)

    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta_p.add_run(f"{analysis_date}  ·  Confidence: {confidence:.0%}")
    set_run_style(run, 11, color=_TEXT_MUTED)

    # Signal badge line
    sig_p = doc.add_paragraph()
    sig_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fg, _ = _SIGNAL_COLOURS.get(content.recommendation, (_TEXT, _IVORY_DARK))
    run = sig_p.add_run(f"  {content.recommendation}  ")
    set_run_style(run, 14, bold=True, color=fg)

    doc.add_paragraph()  # spacer

    # ── Executive Summary ─────────────────────────────────────────────────────
    if content.executive_summary:
        h = doc.add_heading("Executive Summary", level=1)
        h.runs[0].font.color.rgb = rgb(_CLAY_DEEP)
        h.runs[0].font.name = "Calibri"

        para = doc.add_paragraph(content.executive_summary)
        para.runs[0].font.size = Pt(11)
        para.runs[0].font.name = "Calibri"
        para.runs[0].font.color.rgb = rgb(_TEXT)
        para.paragraph_format.space_after = Pt(8)
        doc.add_paragraph()

    # ── Key Metrics table ─────────────────────────────────────────────────────
    if content.metrics:
        h = doc.add_heading("Key Metrics", level=1)
        h.runs[0].font.color.rgb = rgb(_CLAY_DEEP)
        h.runs[0].font.name = "Calibri"

        items = list(content.metrics.items())
        # 2-column table (label + value)
        tbl = doc.add_table(rows=len(items) + 1, cols=2)
        tbl.style = "Table Grid"
        # Header row
        hdr_cells = tbl.rows[0].cells
        for ci, txt in enumerate(["Metric", "Value"]):
            hdr_cells[ci].text = txt
            run = hdr_cells[ci].paragraphs[0].runs[0]
            run.font.bold = True
            run.font.size = Pt(10)
            run.font.name = "Calibri"
            run.font.color.rgb = rgb(_WHITE)
            # Cell background
            tc = hdr_cells[ci]._tc
            tcPr = tc.get_or_add_tcPr()
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), _CLAY)
            tcPr.append(shd)

        for ri, (label, value) in enumerate(items):
            row_cells = tbl.rows[ri + 1].cells
            row_cells[0].text = label
            row_cells[1].text = value
            for cell in row_cells:
                r = cell.paragraphs[0].runs[0]
                r.font.size = Pt(10)
                r.font.name = "Calibri"
            row_cells[0].paragraphs[0].runs[0].font.bold = True
            row_cells[0].paragraphs[0].runs[0].font.color.rgb = rgb(_CLAY_DEEP)
            if ri % 2 == 0:
                for cell in row_cells:
                    tc = cell._tc
                    tcPr = tc.get_or_add_tcPr()
                    shd = OxmlElement("w:shd")
                    shd.set(qn("w:val"), "clear")
                    shd.set(qn("w:color"), "auto")
                    shd.set(qn("w:fill"), "F3F1EA")
                    tcPr.append(shd)

        doc.add_paragraph()

    # ── Analysis sections ─────────────────────────────────────────────────────
    for section in content.sections:
        if not section.title and not section.body:
            continue
        if section.title:
            h = doc.add_heading(section.title, level=2)
            for run in h.runs:
                run.font.color.rgb = rgb(_CLAY)
                run.font.name = "Calibri"
        if section.body:
            # Split on bullet markers and blank lines for clean paragraphs
            for block in section.body.split("\n\n"):
                block = block.strip()
                if not block:
                    continue
                if block.startswith("•"):
                    for line in block.split("\n"):
                        line = line.strip().lstrip("•").strip()
                        if line:
                            para = doc.add_paragraph(line, style="List Bullet")
                            if para.runs:
                                para.runs[0].font.size = Pt(11)
                                para.runs[0].font.name = "Calibri"
                else:
                    para = doc.add_paragraph(block)
                    if para.runs:
                        para.runs[0].font.size = Pt(11)
                        para.runs[0].font.name = "Calibri"
                        para.runs[0].font.color.rgb = rgb(_TEXT)
                    para.paragraph_format.space_after = Pt(6)
        doc.add_paragraph()

    # ── Disclaimer ────────────────────────────────────────────────────────────
    doc.add_paragraph()
    h = doc.add_heading("Disclaimer", level=2)
    for run in h.runs:
        run.font.color.rgb = rgb(_CLAY)
        run.font.name = "Calibri"
    para = doc.add_paragraph(content.disclaimer)
    if para.runs:
        para.runs[0].font.size = Pt(9)
        para.runs[0].font.italic = True
        para.runs[0].font.color.rgb = rgb(_TEXT_MUTED)
        para.runs[0].font.name = "Calibri"

    # Footer
    section_obj = doc.sections[0]
    footer = section_obj.footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run(f"Generated by FinSight  ·  {analysis_date}")
    run.font.size = Pt(8)
    run.font.color.rgb = rgb(_TEXT_MUTED)
    run.font.name = "Calibri"

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
